version: "3.4"

services:
  app:
    build:
      context: .
      dockerfile: infrastructure/docker/Dockerfile
      target: dev
    volumes:
      - ./:/code
    working_dir: /code
    command: ["./mvnw spring-boot:run"]
    depends_on:
      - postgres
    tty: true
    environment:
      SERVER_PORT: ${SERVER_PORT}
      POSTGRES_URL: ${POSTGRES_URL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      LOG_APPLICATION_NAME: ${LOG_APPLICATION_NAME}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"

  postgres:
    image: postgres:11
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
